# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv (Python 3.12)
        uses: astral-sh/setup-uv@v6.6.0
        with:
          python-version: "3.12"
          activate-environment: true
          enable-cache: true

      - name: Set timezone
        run: sudo timedatectl set-timezone Europe/Vienna

      - name: Run pre-commit with prek
        run: uv run --dev prek run -a

      - name: Test with pytest
        run: uv run --dev pytest

      - name: Resolve DetectMateService branch
        run: |
          CURRENT_BRANCH="${{ github.ref_name }}"
          REPO_URL="https://github.com/ait-detectmate/DetectMateService.git"
          if [ "$CURRENT_BRANCH" = "main" ]; then
            echo "DETECTMATE_BRANCH=main" >> $GITHUB_ENV
          elif git ls-remote --heads "$REPO_URL" "$CURRENT_BRANCH" | grep -q .; then
            echo "DETECTMATE_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
          else
            echo "DETECTMATE_BRANCH=development" >> $GITHUB_ENV
          fi

      # integration tests for DetectMateService
      - name: Checkout DetectMateService
        uses: actions/checkout@v4
        with:
          repository: ait-detectmate/DetectMateService
          ref: ${{ env.DETECTMATE_BRANCH }}
          path: DetectMateService

      - name: Prepare DetectMateService (using local DetectMateLibrary)
        working-directory: DetectMateService
        run: |
          # remove the git-based dependency so we don't override the local lib
          sed -i '/detectmatelibrary @ git+/d' pyproject.toml

      - name: Prepare packages
        working-directory: DetectMateService
        run: uv pip install .

      - name: Run DetectMateService library integration tests
        working-directory: DetectMateService
        run: pytest tests/library_integration
