# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "ci_pipe"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv (Python 3.12)
        uses: astral-sh/setup-uv@v6.6.0
        with:
          python-version: "3.12"
          activate-environment: true
          enable-cache: true

      - name: Set timezone
        run: sudo timedatectl set-timezone Europe/Vienna

      - name: Install project deps
        run: uv pip install .[dev]

      - name: Test with pytest
        run: uv run pytest

      # integration tests for DetectMateService
      - name: Checkout DetectMateService
        uses: actions/checkout@v4
        with:
          repository: ait-detectmate/DetectMateService
          path: DetectMateService

      - name: Install DetectMateService (using local DetectMateLibrary)
        working-directory: DetectMateService
        run: |
          sed -i '/detectmatelibrary @ git+/d' pyproject.toml
          uv pip install .[dev]

      - name: Run DetectMateService library integration tests
        working-directory: DetectMateService
        run: uv run pytest tests_libraryintegration
