# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "development" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv (Python 3.12)
        uses: astral-sh/setup-uv@v6.6.0
        with:
          python-version: "3.12"
          activate-environment: true
          enable-cache: true

      - name: Force shared uv virtual environment
        run: echo "UV_PROJECT_ENVIRONMENT=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV

      - name: Set timezone
        run: sudo timedatectl set-timezone Europe/Vienna

      - name: Run pre-commit with prek
        run: uv run --dev prek run -a

      - name: Test with pytest
        run: uv run --dev pytest -s

      # include following code into the run section to match DetectMateService and DetectMateLibrary branches, if the name matches.
      # REPO_URL="https://github.com/ait-detectmate/DetectMateService.git"
      # elif git ls-remote --heads "$REPO_URL" "$CURRENT_BRANCH" | grep -q .; then
      #   echo "SERVICE_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
      - name: Resolve DetectMateService branch
        run: |
          CURRENT_BRANCH="${{ github.ref_name }}"
          if [ "$CURRENT_BRANCH" = "main" ]; then
            echo "SERVICE_BRANCH=main" >> $GITHUB_ENV
          else
            echo "SERVICE_BRANCH=development" >> $GITHUB_ENV
          fi

      # integration tests for DetectMateService
      - name: Checkout DetectMateService
        uses: actions/checkout@v4
        with:
          repository: ait-detectmate/DetectMateService
          ref: ${{ env.SERVICE_BRANCH }}
          path: DetectMateService

      - name: Prepare DetectMateService (using local DetectMateLibrary)
        working-directory: DetectMateService
        run: |
          # remove the git-based dependency so we don't override the local lib
          sed -i '/detectmatelibrary @ git+/d' pyproject.toml

      - name: Prepare packages
        working-directory: DetectMateService
        run: uv pip install .

      #- name: Run DetectMateService library integration tests
      #  working-directory: DetectMateService
      #  run: uv run --dev pytest tests/library_integration -s
